## Swimming PSB Challenge

> In the challenge you'll be wrangling the the `swimming_psb` data set to produce the output shown at the bottom of this notebook.

> Keep a [Cheatsheet](https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf) handy? or the [Pandas API Reference in Docs](https://pandas.pydata.org/pandas-docs/stable/reference/index.html)?

In [ ]:
import pandas as pd

psb_df = pd.read_csv('data/swimming_psb_data.csv')

psb_df.info()
psb_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16948 entries, 0 to 16947
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   c_Sport        16948 non-null  object
 1   c_Season       16948 non-null  int64 
 2   c_Event        16948 non-null  object
 3   c_Gender       16948 non-null  object
 4   n_DateSort     16948 non-null  int64 
 5   c_Person       16640 non-null  object
 6   c_PersonNatio  16640 non-null  object
 7   c_NOC          16948 non-null  object
 8   c_Result       16948 non-null  object
 9   n_ResultSort   16948 non-null  int64 
 10  c_Class        16948 non-null  object
dtypes: int64(3), object(8)
memory usage: 1.4+ MB


c_Sport  c_Season          c_Event c_Gender  n_DateSort  \
0  Swimming      2018  100m Backstroke      Men    20180809   
1  Swimming      2018  100m Backstroke      Men    20180822   
2  Swimming      2018  100m Backstroke      Men    20180806   
3  Swimming      2018  100m Backstroke      Men    20180819   
4  Swimming      2018  100m Backstroke      Men    20180728   

             c_Person  c_PersonNatio          c_NOC c_Result  n_ResultSort  \
0         Ryan Murphy  United States  United States    51.94         51940   
1            Xu Jiayu          China          China    52.30         52300   
2  Kliment Kolesnikov         Russia         Russia    52.51         52510   
3        Ryosuke Irie          Japan          Japan    52.53         52530   
4        Matt Grevers  United States  United States    52.55         52550   

  c_Class  
0   Elite  
1   Elite  
2   Elite  
3   Elite  
4   Elite

#### 1. Remove ```c_Sport```, ```c_Season``` and ```c_Class``` columns.
> Because you decide you don't need them...

#### 2. Output all unique events (```c_Event```).
> Becasue you want to checkout which Swimming events are in the data.

#### 3a. Find all rows with NaN values.
> Because you want to identify where these values are coming from...more examples [here](https://datatofish.com/rows-with-nan-pandas-dataframe/).

In [ ]:
# Example

# rows_with_nan_values = psb_df[psb_df.isnull().any(axis=1)]
# rows_with_nan_values

#### 3b. Find all Unique values in the ```c_Event``` column from the ```rows_with_nan_values``` you created above.
> Because you want to confirm all the NaN values are coming specificly from relay events maybe???

#### 4. Drop all rows in `psb_df` with a NaN values. 
> There are several solutions here...you could actually try provide a value for the missing data...however, in this instance, you decide it's ok to just drop all the rows with NaN values.

#### 5. Reset the Index
> Because you've removed some rows, you decide to reset your Dataframe's index (not nessesity in this case, but good practice to do so)

#### 6. Rename all the column headers in the dataframe, so each header makes sense to you...
> e.g. rename ```c_Person``` to ```athlete```...

#### 7. Transform each value in the ```date_sort``` column into a DateTime Object using the [```.to_datetime```](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html) method.
> Because it's better to handle dates as actual DateTime objects in Python...

#### 8. Create a column for each athlete's ```first name``` and ```last name```.
> Seems futile, but you decide this may save you ALOT of time in the future...

#### Finale: Have a final Dataframe that contains only the top (up to 4) Great British swimmers for each event and gender. Then save this data into a new csv or json file.
> Hint: The dataset you have been handling is already sorted and grouped. Fastest swimmers (top four) would be at the top of each group (gender/event).

### Bonus

**The aim is to create a visualisation** that shows the performance standards for each gender and event relative to the respective world record at the time. This visualisation uses world record times (2018) found in the `world_records_swimming.json` file (`data` folder). To enable a visualisation that can show both genders and all the events, at once, requires us to standardise the results data. We can do this by creating another ***result*** that is the relevent world record as a percentage of the actual result e.g.


> **Men 100m Backstroke - Ryan Murphy, United States - `51.94` (seconds) or `51940` (milliseconds)**


In [ ]:
import json

wrs = json.load(open('data/world_records_swimming.json'))

wr_secs = float(wrs['Men']['100m Backstroke'])
result = 51.94

wr_percentage = wr_secs / result * 100

round(wr_percentage, 2)


99.83

> Hints

1. Include any relevant cleaning steps in the cell below before attempting to create the new column with the percentage data.
2. Note that some of the world record times are not in seconds. It may be an idea to reformat the world records into milliseconds?
3. We import [```seaborn```](https://seaborn.pydata.org/generated/seaborn.violinplot.html) to create the Violin Plots. e.g. https://seaborn.pydata.org/generated/seaborn.violinplot.html

In [ ]:
import json
import pandas as pd
import seaborn as sns

wrs = json.load(open('data/world_records_swimming.json'))  # Pandas is not always nessisary when handling data, a simple dictionary can be far simpler to handle ;)

psb_viz_df = pd.read_csv('data/swimming_psb_data.csv')


##### Reference Image
![BonusViz](./data/swimming_challenge.png)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=01834284-5a22-433a-9a28-a120736ff2ec' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>